# Site settings
title: Denver Data Visualization Template
timestamp: July 2014
email: your-email@domain.com
description: "The starting point for all Denver CfA visualizations."
baseurl: ""
url: "http://yourdomain.com"
share: "Share this."

about:
  label: "Last updated"
  description: "The information presented here is a representation of Open Data provided by the City and County of Denver."

# Footer settings
footer:
  image: "images/flag_tag.svg"
  alt: "Code for America"
  link: "http://codeforamerica.org/"

# Build settings
markdown: kramdown
permalink: pretty

# Custom collections
collections:
- big_numbers
- graphs